server:
  port : 8080
spring:
  cloud:
    gateway:
      httpclient:
        connect-timeout: 1000
        response-timeout: 5s
  security:
    user:
      name: user
      password: pass
gateway:
  a-url: http://savings-service-a:8081
  b-url: http://savings-service-b:8082
